//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIOMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionWaterTax
    {
        public int ReceiptNo { get; set; }
        public decimal Current { get; set; }
        public decimal Previous { get; set; }
        public decimal Second { get; set; }
        public decimal Third { get; set; }
        public decimal MoreThanThree { get; set; }
        public decimal InterestTotal { get; set; }
    
        public virtual Receipt Receipt { get; set; }
    }
}
