//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIOMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionMovementMiscRevenue
    {
        public long id { get; set; }
        public int FromVillageId { get; set; }
        public int ToVillageId { get; set; }
        public string Year { get; set; }
        public Nullable<decimal> Current { get; set; }
        public Nullable<decimal> Arrear { get; set; }
    
        public virtual Village VillageFrom { get; set; }
        public virtual Village VillageTo { get; set; }
    }
}
