//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIOMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionOLR
    {
        public int ReceiptNo { get; set; }
        public int CaseId { get; set; }
        public decimal Premium { get; set; }
        public decimal DemarcationFee { get; set; }
    
        public virtual Receipt Receipt { get; set; }
    }
}
