//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIOMS.Domain
{
    using System;
    
    public partial class ComeFromVillageCess
    {
        public string FromVillage { get; set; }
        public Nullable<int> ToVillage { get; set; }
        public Nullable<decimal> Current { get; set; }
        public Nullable<decimal> Previous { get; set; }
        public Nullable<decimal> Second { get; set; }
        public Nullable<decimal> Third { get; set; }
        public Nullable<decimal> MoreThanThree { get; set; }
    }
}
