//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIOMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Defaulter
    {
        public Defaulter()
        {
            this.Cess = new CessDefaulter();
            this.CBWR = new CBWRDefaulter();
        }
    
        public string KhataNo { get; set; }
        public string Year { get; set; }
        public int VillageId { get; set; }
        public string NameOfRT { get; set; }
    
        public CessDefaulter Cess { get; set; }
        public CBWRDefaulter CBWR { get; set; }
    
        public virtual Village Village { get; set; }
    }
}
