//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIOMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandCess
    {
        public string KhataNo { get; set; }
        public int VillageId { get; set; }
        public string Year { get; set; }
        public decimal Current { get; set; }
        public decimal Previous { get; set; }
        public decimal Second { get; set; }
        public decimal Third { get; set; }
        public decimal MoreThanThree { get; set; }
        public decimal Advance { get; set; }
    
        public virtual Khata Khata { get; set; }
        public virtual Village Village { get; set; }
        public virtual AdvanceAdjustmentCess AdvanceAdjustmentCess { get; set; }
        public virtual AdvanceCollectionCess AdvanceCollectionCess { get; set; }
    }
}
