//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIOMS.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EFDbContext : DbContext
    {
        public EFDbContext()
            : base("name=EFDbContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DemandCess> DemandCesses { get; set; }
        public virtual DbSet<DemandWaterTax> DemandWaterTaxes { get; set; }
        public virtual DbSet<IForm> IForms { get; set; }
        public virtual DbSet<Khata> Khatas { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<Village> Villages { get; set; }
        public virtual DbSet<PlotDetail> PlotDetails { get; set; }
        public virtual DbSet<CollectionCess> CollectionCesses { get; set; }
        public virtual DbSet<CollectionLandRevenue> CollectionLandRevenues { get; set; }
        public virtual DbSet<CollectionMiscRevenue> CollectionMiscRevenues { get; set; }
        public virtual DbSet<CollectionOther> CollectionOthers { get; set; }
        public virtual DbSet<CollectionWaterTax> CollectionWaterTaxes { get; set; }
        public virtual DbSet<MiscRevenue> MiscRevenues { get; set; }
        public virtual DbSet<RICircle> RICircles { get; set; }
        public virtual DbSet<TypesOfMiscRev> TypesOfMiscRevs { get; set; }
        public virtual DbSet<OLRCas> OLRCases { get; set; }
        public virtual DbSet<CollectionOLR> CollectionOLRs { get; set; }
        public virtual DbSet<IFormDetailMiscRevenue> IFormDetailMiscRevenues { get; set; }
        public virtual DbSet<IFormDetailOLR> IFormDetailOLRs { get; set; }
        public virtual DbSet<IFormDetailOther> IFormDetailOthers { get; set; }
        public virtual DbSet<IFormDetailCess> IFormDetailCesses { get; set; }
        public virtual DbSet<IFormDetailLandRevenue> IFormDetailLandRevenues { get; set; }
        public virtual DbSet<IFormDetailWaterTax> IFormDetailWaterTaxes { get; set; }
        public virtual DbSet<CollectionOPDR> CollectionOPDRs { get; set; }
        public virtual DbSet<VillageWiseDemandCess> VillageWiseDemandCesses { get; set; }
        public virtual DbSet<AdvanceCollectionCess> AdvanceCollectionCesses { get; set; }
        public virtual DbSet<AdvanceAdjustmentCess> AdvanceAdjustmentCesses { get; set; }
        public virtual DbSet<AdvanceAdjustmentWaterTax> AdvanceAdjustmentWaterTaxes { get; set; }
        public virtual DbSet<WaterTaxDefaulter> WaterTaxDefaulters { get; set; }
        public virtual DbSet<CollectionMovementCess> CollectionMovementCesses { get; set; }
        public virtual DbSet<Defaulter> Defaulters { get; set; }
        public virtual DbSet<VillageWiseDemandLandRevenue> VillageWiseDemandLandRevenues { get; set; }
        public virtual DbSet<VillageWiseDemandWaterTax> VillageWiseDemandWaterTaxes { get; set; }
        public virtual DbSet<AdvanceCollectionWaterTax> AdvanceCollectionWaterTaxes { get; set; }
        public virtual DbSet<DemandLandRevenue> DemandLandRevenues { get; set; }
        public virtual DbSet<TahCollectionCess> TahCollectionCesses { get; set; }
        public virtual DbSet<TahCollectionLandRevenue> TahCollectionLandRevenues { get; set; }
        public virtual DbSet<TahCollectionMiscRevenue> TahCollectionMiscRevenues { get; set; }
        public virtual DbSet<TahCollectionWaterTax> TahCollectionWaterTaxes { get; set; }
        public virtual DbSet<TahReceipt> TahReceipts { get; set; }
        public virtual DbSet<VillageWiseTahCollectionCess> VillageWiseTahCollectionCesses { get; set; }
        public virtual DbSet<VillageWiseTahCollectionLandRevenue> VillageWiseTahCollectionLandRevenues { get; set; }
        public virtual DbSet<VillageWiseTahCollectionMiscRevenue> VillageWiseTahCollectionMiscRevenues { get; set; }
        public virtual DbSet<VillageWiseTahCollectionWaterTax> VillageWiseTahCollectionWaterTaxes { get; set; }
        public virtual DbSet<AdvanceCollectionLandRevenue> AdvanceCollectionLandRevenues { get; set; }
        public virtual DbSet<IFormDetailOPDR> IFormDetailOPDRs { get; set; }
        public virtual DbSet<DemandMiscRevenue> DemandMiscRevenues { get; set; }
        public virtual DbSet<CollectionMovementMiscRevenue> CollectionMovementMiscRevenues { get; set; }
        public virtual DbSet<PlotsWithRT> PlotsWithRTs { get; set; }
    
        public virtual ObjectResult<SadarSiha> GetSadarSiha(Nullable<int> challanNo, string year)
        {
            var challanNoParameter = challanNo.HasValue ?
                new ObjectParameter("ChallanNo", challanNo) :
                new ObjectParameter("ChallanNo", typeof(int));
    
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SadarSiha>("GetSadarSiha", challanNoParameter, yearParameter);
        }
    
        public virtual ObjectResult<VillageWari> GetVillageWari(Nullable<int> challanNo, Nullable<int> villageId, string year)
        {
            var challanNoParameter = challanNo.HasValue ?
                new ObjectParameter("ChallanNo", challanNo) :
                new ObjectParameter("ChallanNo", typeof(int));
    
            var villageIdParameter = villageId.HasValue ?
                new ObjectParameter("VillageId", villageId) :
                new ObjectParameter("VillageId", typeof(int));
    
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VillageWari>("GetVillageWari", challanNoParameter, villageIdParameter, yearParameter);
        }
    
        public virtual int GetDefaultder(Nullable<int> villageId, string year)
        {
            var villageIdParameter = villageId.HasValue ?
                new ObjectParameter("VillageId", villageId) :
                new ObjectParameter("VillageId", typeof(int));
    
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDefaultder", villageIdParameter, yearParameter);
        }
    
        public virtual int GetDCBMiscRevenue(Nullable<int> villageId, string year)
        {
            var villageIdParameter = villageId.HasValue ?
                new ObjectParameter("VillageId", villageId) :
                new ObjectParameter("VillageId", typeof(int));
    
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDCBMiscRevenue", villageIdParameter, yearParameter);
        }
    
        public virtual ObjectResult<ComeFromVillageCess> GetComeFromVillagesCess(Nullable<int> villageId, string year)
        {
            var villageIdParameter = villageId.HasValue ?
                new ObjectParameter("VillageId", villageId) :
                new ObjectParameter("VillageId", typeof(int));
    
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ComeFromVillageCess>("GetComeFromVillagesCess", villageIdParameter, yearParameter);
        }
    
        public virtual ObjectResult<GoToVillageCess> GetGoToVillagesCess(Nullable<int> villageId, string year)
        {
            var villageIdParameter = villageId.HasValue ?
                new ObjectParameter("VillageId", villageId) :
                new ObjectParameter("VillageId", typeof(int));
    
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GoToVillageCess>("GetGoToVillagesCess", villageIdParameter, yearParameter);
        }
    }
}
