//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIOMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IForm
    {
        public IForm()
        {
            this.IFormDetailMiscRevenues = new HashSet<IFormDetailMiscRevenue>();
            this.IFormDetailOLRs = new HashSet<IFormDetailOLR>();
            this.IFormDetailOthers = new HashSet<IFormDetailOther>();
            this.IFormDetailCesses = new HashSet<IFormDetailCess>();
            this.IFormDetailLandRevenues = new HashSet<IFormDetailLandRevenue>();
            this.IFormDetailWaterTaxes = new HashSet<IFormDetailWaterTax>();
            this.IFormDetailOPDRs = new HashSet<IFormDetailOPDR>();
        }
    
        public int IFormNo { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<bool> IsDeposited { get; set; }
        public string Year { get; set; }
        public System.DateTime DepositeDate { get; set; }
    
        public virtual ICollection<IFormDetailMiscRevenue> IFormDetailMiscRevenues { get; set; }
        public virtual ICollection<IFormDetailOLR> IFormDetailOLRs { get; set; }
        public virtual ICollection<IFormDetailOther> IFormDetailOthers { get; set; }
        public virtual ICollection<IFormDetailCess> IFormDetailCesses { get; set; }
        public virtual ICollection<IFormDetailLandRevenue> IFormDetailLandRevenues { get; set; }
        public virtual ICollection<IFormDetailWaterTax> IFormDetailWaterTaxes { get; set; }
        public virtual ICollection<IFormDetailOPDR> IFormDetailOPDRs { get; set; }
    }
}
