//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIOMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IFormDetailCess
    {
        public int IFormNo { get; set; }
        public Nullable<decimal> Current { get; set; }
        public Nullable<decimal> Previous { get; set; }
        public Nullable<decimal> Second { get; set; }
        public Nullable<decimal> Third { get; set; }
        public Nullable<decimal> MoreThanThree { get; set; }
        public string Year { get; set; }
        public int VillageId { get; set; }
        public Nullable<decimal> InterestTotal { get; set; }
        public System.DateTime DepositeDate { get; set; }
    
        public virtual IForm IForm { get; set; }
        public virtual Village Village { get; set; }
    }
}
