//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIOMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khata
    {
        public Khata()
        {
            this.DemandCesses = new HashSet<DemandCess>();
            this.DemandWaterTaxes = new HashSet<DemandWaterTax>();
            this.Receipts = new HashSet<Receipt>();
            this.PlotDetails = new HashSet<PlotDetail>();
            this.WaterTaxDefaulter = new HashSet<WaterTaxDefaulter>();
            this.DemandLandRevenues = new HashSet<DemandLandRevenue>();
            this.TahReceipts = new HashSet<TahReceipt>();
        }
    
        public string KhataNo { get; set; }
        public int VillageId { get; set; }
        public string NameOfRT { get; set; }
        public Nullable<decimal> Khajana { get; set; }
        public Nullable<decimal> Cess { get; set; }
        public Nullable<decimal> JalaKara { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public string Status { get; set; }
        public string SpecialCase { get; set; }
        public Nullable<bool> HasPlots { get; set; }
    
        public virtual ICollection<DemandCess> DemandCesses { get; set; }
        public virtual ICollection<DemandWaterTax> DemandWaterTaxes { get; set; }
        public virtual ICollection<Receipt> Receipts { get; set; }
        public virtual Village Village { get; set; }
        public virtual ICollection<PlotDetail> PlotDetails { get; set; }
        public virtual ICollection<WaterTaxDefaulter> WaterTaxDefaulter { get; set; }
        public virtual ICollection<DemandLandRevenue> DemandLandRevenues { get; set; }
        public virtual ICollection<TahReceipt> TahReceipts { get; set; }
    }
}
