//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIOMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiscRevenue
    {
        public MiscRevenue()
        {
            this.IsPaid = false;
            this.Receipts = new HashSet<Receipt>();
            this.DemandMiscRevenues = new HashSet<DemandMiscRevenue>();
            this.TahReceipts = new HashSet<TahReceipt>();
        }
    
        public string Name { get; set; }
        public string Father_HusbandName { get; set; }
        public int Id { get; set; }
        public int Year { get; set; }
        public string CaseNo { get; set; }
        public decimal Amount { get; set; }
        public string FYear { get; set; }
        public int VillageId { get; set; }
        public int TypeId { get; set; }
        public Nullable<bool> IsPaid { get; set; }
    
        public virtual Village Village { get; set; }
        public virtual TypesOfMiscRev TypesOfMiscRev { get; set; }
        public virtual ICollection<Receipt> Receipts { get; set; }
        public virtual ICollection<DemandMiscRevenue> DemandMiscRevenues { get; set; }
        public virtual ICollection<TahReceipt> TahReceipts { get; set; }
    }
}
