//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIOMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OLRCas
    {
        public int VillageId { get; set; }
        public int CaseNo { get; set; }
        public int Year { get; set; }
        public int Id { get; set; }
    
        public virtual Village Village { get; set; }
    }
}
