//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIOMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlotDetail
    {
        public string KhataNo { get; set; }
        public int VillageId { get; set; }
        public string PlotNo { get; set; }
        public string Kisam { get; set; }
        public Nullable<double> Acre { get; set; }
        public Nullable<double> Decimal { get; set; }
        public Nullable<decimal> Area { get; set; }
        public string Remark { get; set; }
        public string ChauhadiNorth { get; set; }
        public string ChakaName { get; set; }
        public string ChauhadiSouth { get; set; }
        public string ChauhadiEast { get; set; }
        public string ChauhadiWest { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
    
        public virtual Khata Khata { get; set; }
        public virtual Village Village { get; set; }
    }
}
