//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIOMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlotsWithRT
    {
        public string Name { get; set; }
        public string KhataNo { get; set; }
        public string NameOfRT { get; set; }
        public string PlotNo { get; set; }
        public string Kisam { get; set; }
        public Nullable<decimal> Area { get; set; }
        public int VillageId { get; set; }
    }
}
