//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIOMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public Receipt()
        {
            this.Year = "2014-15";
        }
    
        public int ReceiptNo { get; set; }
        public string KhataNo { get; set; }
        public string Year { get; set; }
        public Nullable<int> VillageId { get; set; }
        public System.DateTime Date { get; set; }
        public string NameOfRT { get; set; }
        public bool IsCanceled { get; set; }
        public Nullable<int> ActualVillageId { get; set; }
        public Nullable<int> MiscId { get; set; }
    
        public virtual Khata Khata { get; set; }
        public virtual Village Village { get; set; }
        public virtual CollectionCess CollectionCess { get; set; }
        public virtual CollectionLandRevenue CollectionLandRevenue { get; set; }
        public virtual CollectionMiscRevenue CollectionMiscRevenue { get; set; }
        public virtual CollectionOther CollectionOther { get; set; }
        public virtual CollectionWaterTax CollectionWaterTax { get; set; }
        public virtual CollectionOLR CollectionOLR { get; set; }
        public virtual CollectionOPDR CollectionOPDR { get; set; }
        public virtual MiscRevenue MiscRevenue { get; set; }
    }
}
