//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIOMS.Domain
{
    using System;
    
    public partial class SadarSiha
    {
        public System.DateTime Date { get; set; }
        public int ReceiptNo { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> LandRevenue { get; set; }
        public Nullable<decimal> Cess { get; set; }
        public Nullable<decimal> WaterRate { get; set; }
        public Nullable<decimal> MiscRevenueCurrent { get; set; }
        public Nullable<decimal> MiscRevenueArrear { get; set; }
        public Nullable<decimal> InterestLR { get; set; }
        public Nullable<decimal> IntrestLR { get; set; }
        public Nullable<decimal> IntrestMisc { get; set; }
        public Nullable<decimal> IntrestCess { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
