//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIOMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TahCollectionMiscRevenue
    {
        public int ReceiptNo { get; set; }
        public string Type { get; set; }
        public string CaseNo { get; set; }
        public decimal Current { get; set; }
        public decimal Arrear { get; set; }
        public decimal Interest { get; set; }
    
        public virtual TahReceipt TahReceipt { get; set; }
    }
}
