//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIOMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TahReceipt
    {
        public int ReceiptNo { get; set; }
        public int VillageId { get; set; }
        public System.DateTime Date { get; set; }
        public string Year { get; set; }
        public string KhataNo { get; set; }
        public Nullable<int> MIscId { get; set; }
    
        public virtual Khata Khata { get; set; }
        public virtual TahCollectionCess TahCollectionCess { get; set; }
        public virtual TahCollectionLandRevenue TahCollectionLandRevenue { get; set; }
        public virtual TahCollectionMiscRevenue TahCollectionMiscRevenue { get; set; }
        public virtual TahCollectionWaterTax TahCollectionWaterTax { get; set; }
        public virtual Village Village { get; set; }
        public virtual MiscRevenue MiscRevenue { get; set; }
    }
}
