//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIOMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Village
    {
        public Village()
        {
            this.Receipts = new HashSet<Receipt>();
            this.Khatas = new HashSet<Khata>();
            this.PlotDetails = new HashSet<PlotDetail>();
            this.MiscRevenues = new HashSet<MiscRevenue>();
            this.OLRCases = new HashSet<OLRCas>();
            this.IFormDetailMiscRevenues = new HashSet<IFormDetailMiscRevenue>();
            this.IFormDetailOLRs = new HashSet<IFormDetailOLR>();
            this.IFormDetailOthers = new HashSet<IFormDetailOther>();
            this.IFormDetailCesses = new HashSet<IFormDetailCess>();
            this.IFormDetailLandRevenues = new HashSet<IFormDetailLandRevenue>();
            this.IFormDetailWaterTaxes = new HashSet<IFormDetailWaterTax>();
            this.DemandCesses = new HashSet<DemandCess>();
            this.DemandWaterTaxes = new HashSet<DemandWaterTax>();
            this.VillageWiseDemandCesses = new HashSet<VillageWiseDemandCess>();
            this.AdvanceCollectionCesses = new HashSet<AdvanceCollectionCess>();
            this.AdvanceAdjustmentCesses = new HashSet<AdvanceAdjustmentCess>();
            this.WaterTaxDefaulters = new HashSet<WaterTaxDefaulter>();
            this.AdvanceAdjustmentWaterTaxes = new HashSet<AdvanceAdjustmentWaterTax>();
            this.CollectionMovementCessesTo = new HashSet<CollectionMovementCess>();
            this.CollectionMovementCessesFrom = new HashSet<CollectionMovementCess>();
            this.Defaulters = new HashSet<Defaulter>();
            this.VillageWiseDemandLandRevenues = new HashSet<VillageWiseDemandLandRevenue>();
            this.VillageWiseDemandWaterTaxes = new HashSet<VillageWiseDemandWaterTax>();
            this.AdvanceCollectionWaterTaxes = new HashSet<AdvanceCollectionWaterTax>();
            this.DemandLandRevenues = new HashSet<DemandLandRevenue>();
            this.TahReceipts = new HashSet<TahReceipt>();
            this.VillageWiseTahCollectionLandRevenues = new HashSet<VillageWiseTahCollectionLandRevenue>();
            this.VillageWiseTahCollectionCesses = new HashSet<VillageWiseTahCollectionCess>();
            this.VillageWiseTahCollectionWaterTaxes = new HashSet<VillageWiseTahCollectionWaterTax>();
            this.VillageWiseTahCollectionMiscRevenues = new HashSet<VillageWiseTahCollectionMiscRevenue>();
            this.AdvanceCollectionLandRevenues = new HashSet<AdvanceCollectionLandRevenue>();
            this.IFormDetailOPDRs = new HashSet<IFormDetailOPDR>();
            this.DemandMiscRevenues = new HashSet<DemandMiscRevenue>();
            this.CollectionMovementMiscRevenuesTo = new HashSet<CollectionMovementMiscRevenue>();
            this.CollectionMovementMiscRevenuesFrom = new HashSet<CollectionMovementMiscRevenue>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int RICircleId { get; set; }
    
        public virtual ICollection<Receipt> Receipts { get; set; }
        public virtual ICollection<Khata> Khatas { get; set; }
        public virtual ICollection<PlotDetail> PlotDetails { get; set; }
        public virtual ICollection<MiscRevenue> MiscRevenues { get; set; }
        public virtual RICircle RICircle { get; set; }
        public virtual ICollection<OLRCas> OLRCases { get; set; }
        public virtual ICollection<IFormDetailMiscRevenue> IFormDetailMiscRevenues { get; set; }
        public virtual ICollection<IFormDetailOLR> IFormDetailOLRs { get; set; }
        public virtual ICollection<IFormDetailOther> IFormDetailOthers { get; set; }
        public virtual ICollection<IFormDetailCess> IFormDetailCesses { get; set; }
        public virtual ICollection<IFormDetailLandRevenue> IFormDetailLandRevenues { get; set; }
        public virtual ICollection<IFormDetailWaterTax> IFormDetailWaterTaxes { get; set; }
        public virtual ICollection<DemandCess> DemandCesses { get; set; }
        public virtual ICollection<DemandWaterTax> DemandWaterTaxes { get; set; }
        public virtual ICollection<VillageWiseDemandCess> VillageWiseDemandCesses { get; set; }
        public virtual ICollection<AdvanceCollectionCess> AdvanceCollectionCesses { get; set; }
        public virtual ICollection<AdvanceAdjustmentCess> AdvanceAdjustmentCesses { get; set; }
        public virtual ICollection<WaterTaxDefaulter> WaterTaxDefaulters { get; set; }
        public virtual ICollection<AdvanceAdjustmentWaterTax> AdvanceAdjustmentWaterTaxes { get; set; }
        public virtual ICollection<CollectionMovementCess> CollectionMovementCessesTo { get; set; }
        public virtual ICollection<CollectionMovementCess> CollectionMovementCessesFrom { get; set; }
        public virtual ICollection<Defaulter> Defaulters { get; set; }
        public virtual ICollection<VillageWiseDemandLandRevenue> VillageWiseDemandLandRevenues { get; set; }
        public virtual ICollection<VillageWiseDemandWaterTax> VillageWiseDemandWaterTaxes { get; set; }
        public virtual ICollection<AdvanceCollectionWaterTax> AdvanceCollectionWaterTaxes { get; set; }
        public virtual ICollection<DemandLandRevenue> DemandLandRevenues { get; set; }
        public virtual ICollection<TahReceipt> TahReceipts { get; set; }
        public virtual ICollection<VillageWiseTahCollectionLandRevenue> VillageWiseTahCollectionLandRevenues { get; set; }
        public virtual ICollection<VillageWiseTahCollectionCess> VillageWiseTahCollectionCesses { get; set; }
        public virtual ICollection<VillageWiseTahCollectionWaterTax> VillageWiseTahCollectionWaterTaxes { get; set; }
        public virtual ICollection<VillageWiseTahCollectionMiscRevenue> VillageWiseTahCollectionMiscRevenues { get; set; }
        public virtual ICollection<AdvanceCollectionLandRevenue> AdvanceCollectionLandRevenues { get; set; }
        public virtual ICollection<IFormDetailOPDR> IFormDetailOPDRs { get; set; }
        public virtual ICollection<DemandMiscRevenue> DemandMiscRevenues { get; set; }
        public virtual ICollection<CollectionMovementMiscRevenue> CollectionMovementMiscRevenuesTo { get; set; }
        public virtual ICollection<CollectionMovementMiscRevenue> CollectionMovementMiscRevenuesFrom { get; set; }
    }
}
