//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIOMS.Domain
{
    using System;
    
    public partial class VillageWari
    {
        public System.DateTime Date { get; set; }
        public int ReceiptNo { get; set; }
        public string NameOfRT { get; set; }
        public Nullable<decimal> LandRevenueCurrent { get; set; }
        public Nullable<decimal> LandRevenuePrevious { get; set; }
        public Nullable<decimal> LandRevenueSecond { get; set; }
        public Nullable<decimal> LandRevenueThird { get; set; }
        public Nullable<decimal> LandRevenueMoreThanThree { get; set; }
        public Nullable<decimal> LandRevenueInterest { get; set; }
        public Nullable<decimal> CessCurrent { get; set; }
        public Nullable<decimal> CessPrevious { get; set; }
        public Nullable<decimal> CessSecond { get; set; }
        public Nullable<decimal> CessThird { get; set; }
        public Nullable<decimal> CessMoreThanThree { get; set; }
        public Nullable<decimal> CessInterest { get; set; }
        public Nullable<decimal> WaterRateCurrent { get; set; }
        public Nullable<decimal> WaterRatePrevious { get; set; }
        public Nullable<decimal> WaterRateSecond { get; set; }
        public Nullable<decimal> WaterRateThird { get; set; }
        public Nullable<decimal> WaterRateMoreThanThree { get; set; }
        public Nullable<decimal> WaterRateInterest { get; set; }
    }
}
